biblio/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from crm_app.views import ClientViewSet, ContactViewSet, OpportunityViewSet, InteractionViewSet
from books.views import AuthorViewSet, GenreViewSet
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

# DOCUMENTATION API #
schema_view = get_schema_view(
   openapi.Info(
      title="API CRM",
      default_version='v1',
      description="Documentation de l'API CRM",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@crm.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

# ROUTE D'API #

router = DefaultRouter()

# ROUTE D'API POUR CRM APP#

router.register(r'clients', ClientViewSet)
router.register(r'contacts', ContactViewSet)
router.register(r'opportunities', OpportunityViewSet)

# ROUTE D'API POUR BOOKS APP#

router.register(r'author', AuthorViewSet)
router.register(r'genre', GenreViewSet)

# URL PATTERNS #

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),  # Books app
    path('books/lecteurs/', include('client_library.urls')),  # Books app
    path('', include('crm_app.urls')),  # CRM app
    path('api/', include(router.urls)),  # Incluez les routes de l'API
    path('api/swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('api/redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

books/urls.py
# urls.py
from django.urls import path
from . import views
app_name = 'books'  # Ajoutez cette ligne pour enregistrer le namespace


urlpatterns = [
    path('', views.book_list, name='list'),
    path('create/', views.book_create, name='create'),
    path('create_author/', views.add_author, name='add_author'),
    path('create_genre/', views.add_genre, name='add_genre'),
    path('set_language/', views.SetLanguageView.as_view(), name='set_language'),
    path('delete/<int:pk>/', views.book_delete, name='delete'),
]

templates/base.html
<!DOCTYPE html>
{% load i18n %}

<html>
<head>
    <title>App Livres</title>
    <header>
    </header>
</head>
<body>
    <header>
    <p>LANGUAGE_CODE: {{ request.LANGUAGE_CODE }}</p>

    <form action="{% url 'books:set_language' %}" method="post">
      {% csrf_token %}
      <select name="language" onchange="this.form.submit()">
          <option value="fr" {% if request.LANGUAGE_CODE == 'fr' %}selected{% endif %}>🇫🇷 Français</option>
          <option value="en" {% if request.LANGUAGE_CODE == 'en' %}selected{% endif %}>🇬🇧 English</option>
          <option value="es" {% if request.LANGUAGE_CODE == 'es' %}selected{% endif %}>Espanol</option>
      </select>
  </form>
</header>
{% block content %}{% endblock %}

</body><footer></footer>
</html>